*----------------------------------------------------------------------
* GPUBMA Phase 2 — Stata validation oracle (medium model space)
* Dataset : data/synthetic/panel_12.dta (frozen, generated by Python)
* Model   : y on optional x1-x12; always-included controls w1 w2
* Fixed effects: none
* Model space: 2^12 = 4,096 candidate models (exhaustive enumeration)
*
* Priors are fixed and documented to match the Python reference exactly:
*   g-prior      : fixed g = 1000  (Python default benchmark g = max(n, p^2)
*                  = max(1000, 144) = 1000 for this dataset; passing it
*                  explicitly keeps the run deterministic)
*   model prior  : beta-binomial(1, 1)
* Convention (verified 2026-07-15 on StataNow/SE 19.5): flat intercept,
* optional and always slopes jointly under the g-prior; Stata's model size
* counts always-included variables (subtract e(p_always) for Python parity).
*----------------------------------------------------------------------
version 18
clear all
set more off
set linesize 120

* run from the repository root:  do validation/stata/medium_no_fixed_effects.do
capture mkdir "validation/stata/output"
log using "validation/stata/output/medium_no_fixed_effects.log", replace text

display "Stata version: " c(stata_version)
display "Edition: " c(edition_real)
display "Born: " c(born_date)

use "data/synthetic/panel_12.dta", clear

* -- validate the frozen data ------------------------------------------
assert _N == 1000
confirm variable individual_id period y x1 x2 x3 x4 x5 x6 x7 x8 x9 x10 x11 x12 w1 w2
isid individual_id period
describe
summarize

* -- exhaustive BMA (enumeration explicitly requested, never sampling) --
* saving() writes the per-model dataset (inclusion masks + PMPs for all
* 4,096 models) — the only complete per-model export path; bmastats models
* top(#) cannot report more than ~2,500 ranks (numlist cap, verified).
bmaregress y x1-x12 (w1 w2, always), ///
    enumeration ///
    gprior(fixed 1000) ///
    mprior(betabinomial 1 1) ///
    saving("validation/stata/output/medium_no_fe_models", replace)

describe using "validation/stata/output/medium_no_fe_models.dta"

* -- record everything the estimation stored ---------------------------
ereturn list

* posterior summaries (also captured in this plain-text log)
bmastats models, top(20)
return list
bmastats pip
bmastats msize
return list

* -- machine-readable exports (no manual copying of output) ------------
* Matrix names confirmed from `ereturn list` on Stata 19.5 (StataNow, SE):
* e(b_bma) = BMA posterior means, e(V_bma) = BMA posterior covariance,
* e(pip) = posterior inclusion probabilities. There is no e(b).
matrix b_bma = e(b_bma)
matrix pip = e(pip)
matrix vdiag = vecdiag(e(V_bma))
local names : colnames e(b_bma)
file open fh using "validation/stata/output/medium_no_fe_colnames.txt", write replace
file write fh `"`names'"'
file close fh

* NOTE on per-model exports: `bmastats models, top(#)` cannot report the
* full model space — top(4096) fails (numlist cap, r(123)) and r(summary)
* holds at most 50 rows per call (both verified on StataNow/SE 19.5).
* The complete per-model record (inclusion states, log posterior, log
* model prior, conditional moments) comes from the bmaregress saving()
* dataset exported above: medium_no_fe_models.dta.

preserve
clear
svmat double b_bma
export delimited using "validation/stata/output/medium_no_fe_b_bma.csv", replace
clear
svmat double pip
export delimited using "validation/stata/output/medium_no_fe_pip.csv", replace
clear
svmat double vdiag
export delimited using "validation/stata/output/medium_no_fe_v_diag.csv", replace
clear
set obs 1
gen double msize_mean = e(msize_mean)
gen double msize_mean_prior = e(msize_mean_prior)
gen double p_always = e(p_always)
gen double p_groups = e(p_groups)
gen double g_used = e(g)
gen double shrinkage = e(shrinkage)
gen double sigma2 = e(sigma2)
gen double k_models = e(k_models)
gen double n_obs = e(N)
export delimited using "validation/stata/output/medium_no_fe_scalars.csv", replace
restore

log close
exit, clear
