*----------------------------------------------------------------------
* GPUBMA Phase 1 — Stata validation oracle
* Dataset : data/synthetic/panel_8.dta (frozen, generated by Python)
* Model   : y on optional x1-x8; always-included controls w1 w2
* Fixed effects: none
*
* STATUS: PREPARED, NOT YET EXECUTED. No working Stata installation was
* available on the development machine (only renamed StataSE-64_old.exe
* leftovers that do not run in batch mode). Numbers in the repository do
* NOT come from this script. Requires Stata 18+ (bmaregress).
*
* Priors are fixed and documented to match the Python reference exactly:
*   g-prior      : fixed g = 1000  (Python default benchmark g = max(n, p^2)
*                  = max(1000, 64) = 1000 for this dataset)
*   model prior  : beta-binomial(1, 1)
* NOTE: verify option keywords against `help bmaregress` on first run;
* they follow the [BMA] bmaregress manual but have not been executed here.
*----------------------------------------------------------------------
version 18
clear all
set more off
set linesize 120

* run from the repository root:  do validation/stata/small_no_fixed_effects.do
capture mkdir "validation/stata/output"
log using "validation/stata/output/small_no_fixed_effects.log", replace text

display "Stata version: " c(stata_version)
display "Born: " c(born_date)
about

use "data/synthetic/panel_8.dta", clear

* -- validate the frozen data ------------------------------------------
assert _N == 1000
confirm variable individual_id period y x1 x2 x3 x4 x5 x6 x7 x8 w1 w2
isid individual_id period
describe
summarize

* -- exhaustive BMA (enumeration explicitly requested, never sampling) --
bmaregress y x1-x8 (w1 w2, always), ///
    enumeration ///
    gprior(fixed 1000) ///
    mprior(betabinomial 1 1)

* -- record everything the estimation stored ---------------------------
ereturn list

* posterior summaries (also captured in this plain-text log)
bmastats models, top(20)
bmastats pip
bmastats msize

* -- machine-readable exports (no manual copying of output) ------------
* coefficient posterior means
matrix b = e(b)
preserve
clear
svmat double b, names(col)
export delimited using "validation/stata/output/small_no_fe_e_b.csv", replace
restore

* posterior inclusion probabilities: bmaregress stores them in e();
* the exact matrix name must be confirmed from `ereturn list` above on the
* first real run. The capture block records the attempt without fabricating
* output if the name differs. LIMITATION: cannot be confirmed until a
* working Stata installation is available.
capture noisily {
    matrix PIP = e(pip)
    preserve
    clear
    svmat double PIP, names(col)
    export delimited using "validation/stata/output/small_no_fe_pip.csv", replace
    restore
}

log close
exit, clear
