*----------------------------------------------------------------------
* GPUBMA Phase 1 — Stata validation oracle
* Dataset : data/synthetic/panel_8.dta (frozen, generated by Python)
* Model   : y on optional x1-x8; always-included controls w1 w2
* Fixed effects: none
*
* STATUS: EXECUTED 2026-07-15 in batch mode on StataNow/SE 19.5.
* Option keywords and e() matrix names verified on that run.
*
* Priors are fixed and documented to match the Python reference exactly:
*   g-prior      : fixed g = 1000  (Python default benchmark g = max(n, p^2)
*                  = max(1000, 64) = 1000 for this dataset)
*   model prior  : beta-binomial(1, 1)
*----------------------------------------------------------------------
version 18
clear all
set more off
set linesize 120

* run from the repository root:  do validation/stata/small_no_fixed_effects.do
capture mkdir "validation/stata/output"
log using "validation/stata/output/small_no_fixed_effects.log", replace text

display "Stata version: " c(stata_version)
display "Edition: " c(edition_real)
display "Born: " c(born_date)

use "data/synthetic/panel_8.dta", clear

* -- validate the frozen data ------------------------------------------
assert _N == 1000
confirm variable individual_id period y x1 x2 x3 x4 x5 x6 x7 x8 w1 w2
isid individual_id period
describe
summarize

* -- exhaustive BMA (enumeration explicitly requested, never sampling) --
bmaregress y x1-x8 (w1 w2, always), ///
    enumeration ///
    gprior(fixed 1000) ///
    mprior(betabinomial 1 1)

* -- record everything the estimation stored ---------------------------
ereturn list

* posterior summaries (also captured in this plain-text log)
bmastats models, top(20)
bmastats pip
bmastats msize

* -- machine-readable exports (no manual copying of output) ------------
* Matrix names confirmed from `ereturn list` on Stata 19.5 (StataNow, SE):
* e(b_bma) = BMA posterior means, e(V_bma) = BMA posterior covariance,
* e(pip) = posterior inclusion probabilities. There is no e(b).
matrix b_bma = e(b_bma)
matrix pip = e(pip)
matrix vdiag = vecdiag(e(V_bma))
local names : colnames e(b_bma)
file open fh using "validation/stata/output/small_no_fe_colnames.txt", write replace
file write fh `"`names'"'
file close fh
preserve
clear
svmat double b_bma
export delimited using "validation/stata/output/small_no_fe_b_bma.csv", replace
clear
svmat double pip
export delimited using "validation/stata/output/small_no_fe_pip.csv", replace
clear
svmat double vdiag
export delimited using "validation/stata/output/small_no_fe_v_diag.csv", replace
clear
set obs 1
gen double msize_mean = e(msize_mean)
gen double msize_mean_prior = e(msize_mean_prior)
gen double p_always = e(p_always)
gen double p_groups = e(p_groups)
gen double g_used = e(g)
gen double shrinkage = e(shrinkage)
gen double sigma2 = e(sigma2)
gen double k_models = e(k_models)
gen double n_obs = e(N)
export delimited using "validation/stata/output/small_no_fe_scalars.csv", replace
restore

log close
exit, clear
