*----------------------------------------------------------------------
* GPUBMA Phase 1 — Stata validation oracle
* Dataset : data/synthetic/panel_8.dta (frozen, generated by Python)
* Model   : y on optional x1-x8; always-included w1 w2 + individual AND
*           time dummies (two-way fixed effects)
*
* STATUS: PREPARED, NOT YET EXECUTED (no working Stata on the dev machine).
* Requires Stata 18+ (bmaregress). Verify option keywords via help bmaregress.
* Priors fixed to match Python: g = 1000, beta-binomial(1,1) model prior.
*----------------------------------------------------------------------
version 18
clear all
set more off
set linesize 120
capture mkdir "validation/stata/output"
log using "validation/stata/output/small_two_way_fixed_effects.log", replace text

display "Stata version: " c(stata_version)
about

use "data/synthetic/panel_8.dta", clear
assert _N == 1000
confirm variable individual_id period y x1 x2 x3 x4 x5 x6 x7 x8 w1 w2
isid individual_id period

bmaregress y x1-x8 (w1 w2 i.individual_id i.period, always), ///
    enumeration ///
    gprior(fixed 1000) ///
    mprior(betabinomial 1 1)

ereturn list
bmastats models, top(20)
bmastats pip
bmastats msize

matrix b = e(b)
preserve
clear
svmat double b, names(col)
export delimited using "validation/stata/output/small_two_way_fe_e_b.csv", replace
restore

capture noisily {
    matrix PIP = e(pip)
    preserve
    clear
    svmat double PIP, names(col)
    export delimited using "validation/stata/output/small_two_way_fe_pip.csv", replace
    restore
}

log close
exit, clear
