"""Produce reports/environment_report.{md,json} from gpubma diagnostics
plus repository facts (git status, working tree).

Usage:  python scripts/make_environment_report.py
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from gpubma.diagnostics.doctor import collect_diagnostics, format_report  # noqa: E402


def _git(*args) -> str | None:
    try:
        out = subprocess.run(["git", *args], cwd=ROOT, capture_output=True, text=True, timeout=30)
        return out.stdout.strip() if out.returncode == 0 else None
    except OSError:
        return None


def main() -> int:
    diag = collect_diagnostics()
    diag["repository"] = {
        "root": str(ROOT),
        "git_branch": _git("rev-parse", "--abbrev-ref", "HEAD"),
        "git_head": _git("rev-parse", "HEAD"),
        "git_status_porcelain_lines": len((_git("status", "--porcelain") or "").splitlines()),
        "git_remotes": _git("remote", "-v") or "(none)",
    }
    reports = ROOT / "reports"
    reports.mkdir(exist_ok=True)
    (reports / "environment_report.json").write_text(json.dumps(diag, indent=2))

    md = [
        "# GPUBMA environment report",
        "",
        "Generated by `scripts/make_environment_report.py` (see the JSON twin for raw values).",
        "",
        "```text",
        format_report(diag),
        "```",
        "",
        "## Repository",
        "",
        f"- Root: `{diag['repository']['root']}`",
        f"- Branch: `{diag['repository']['git_branch']}` @ `{diag['repository']['git_head']}`",
        f"- Uncommitted paths: {diag['repository']['git_status_porcelain_lines']}",
        "",
        "## Package managers and compilers",
        "",
        f"- pip: {diag['package_managers']['pip']}, conda: {diag['package_managers']['conda']}, uv: {diag['package_managers']['uv']}",
        f"- nvcc: `{diag['compilers']['nvcc']}`",
        f"- g++: `{diag['compilers']['g++']}`, cl: `{diag['compilers']['cl']}`",
        "",
        "## Key scientific packages",
        "",
    ] + [f"- {k}: {v or 'not installed'}" for k, v in diag["packages"].items()] + [
        "",
        "## Notable findings",
        "",
        f"- GPU: **{diag['summary']['gpu_detected']}** "
        f"(float64 from Python verified: {diag['summary']['cuda_usable_from_python_float64_verified']})",
        f"- nvcc installed: {diag['summary']['nvcc_installed']} "
        "(not required for Phase 1; required later for custom CUDA kernels)",
        f"- Stata installed: {diag['summary']['stata_installed']}, "
        f"callable in batch mode: {diag['summary']['stata_callable']} "
        f"({diag['stata'].get('note') or 'see JSON'}) — "
        + ("the validation oracle scripts have been EXECUTED on this machine"
           if diag["summary"]["stata_callable"]
           else "validation .do scripts are prepared but cannot be executed on this machine"),
        "",
    ]
    (reports / "environment_report.md").write_text("\n".join(md), encoding="utf-8")
    print("\n".join(md))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
